INSERT INTO books (id, title, author,publication, year, created_at, updated_at) VALUES
(1, 'The Adventures of Duck and Goose','Sir Quackalot', 'Hachette Book Group','2012', now(), now()),
(2, 'The Return of Duck and Goose', 'Sir Quackalot','Hachette Book Group','2010', now(), now()),
(3, 'More Fun with Duck and Goose', 'Sir Quackalot','Hachette Book Group','2009', now(), now()),
(4, 'Duck and Goose on Holiday', 'Sir Quackalot','Hachette Book Group','2011', now(), now()),
(5, 'My Friend is a Duck', 'A. Parrot', 'Hachette Book Group','2013', now(), now()),
(6, 'UFO Debunked','Anonymous','PT BukuBagus','2018', now(), now()),
(7, 'Annotated Notes on the Duck and Goose chronicles','Prof Macaw','Macmillan','2013', now(), now()),
(8, 'Duck and Goose Cheat Sheet for Students','Polly Parrot', 'Macmillan','2014', now(), now()),
(9, 'Duck and Goose: an allegory for modern times?','Bor Ing', 'Macmillan','2014', now(), now()),
(10, 'Is UFO Real ??','Enigma','PT BukuBagus','2017', now(), now()),
(11,'Fundamentals of Wavelets','Goswami, Jaideva','Wiley', '2020', now(), now()),
(12,'Data Smart','Foreman, John','Wiley','2021', now(), now()),
(13,'God Created the Integers','Hawking, Stephen','Penguin','2010', now(), now()),
(14,'Superfreakonomics','Dubner, Stephen','HarperCollins','2021', now(), now()),
(15,'Orientalism','Said, Edward','Penguin','2017', now(), now()),
(16,'Nature of Statistical Learning Theory, The','Vapnik, Vladimir','Springer','2018',now(), now()),
(17,'Integration of the Indian States','Menon, V P','Orient Blackswan','2016', now(), now()),
(18,"Drunkard's Walk, The",'Mlodinow, Leonard','Penguin','2000', now(), now()),
(19,"Image Processing & Mathematical Morphology","Shih, Frank","CRC","1992", now(), now()),
(20,"How to Think Like Sherlock Holmes","Konnikova, Maria","Penguin","2010", now(), now()),
(21,"Data Scientists at Work","Sebastian Gutierrez","Apress","2011", now(), now()),
(22,"Slaughterhouse Five","Vonnegut, Kurt","Random House","2012", now(), now()),
(23,"Birth of a Theorem","Villani, Cedric","Bodley Head","2013", now(), now()),
(24,"Structure & Interpretation of Computer Programs","Sussman, Gerald","MIT Press","2014", now(), now()),
(25,"Age of Wrath, The","Eraly, Abraham","Penguin","2015", now(), now()),
(26,"Trial, The","Kafka, Frank","Random House","2016", now(), now()),
(27,"Statistical Decision Theory","Pratt, John","MIT Press","2017", now(), now()),
(28,"Data Mining Handbook","Nisbet, Robert","Apress","2018", now(), now());